### ISSUE TITLE
bug in setting frequency

### ISSUE THREAD

**Issue by MarkusEugen** [Adminius/DimmerZero#1]
in DimmerZero.cpp line 143:

`REG_TCC0_PER = _maxValue;					// Set the frequency of the PWM on TCC0 
`
_maxValue is not the frequency but the amount of the duty cycle.  The Frequency is used a different way as discussed in this [thread](https://forum.arduino.cc/index.php?topic=346731.0)

**Comment by Adminius** [comment]
With amount of duty cycles you can chage PWM frequency.
Is it really a bug or the "wrong wordning" only?

**Comment by MarkusEugen** [comment]
not really a bug but the class as it is only works for your example.  To increase usability it might be better to do this:

`_maxValue = 48000000/(2*div*_frequency);`

and not make the _maxValue user settable.

**Comment by Adminius** [comment]
but it doesn't make sens.
i can't understand, why i should make **_maxValue** not user settable?
default it is 12000. If user will change it, he can do it.
I will make this lib flexible.
For standard cases it make more sence to use analogWrite... https://github.com/arduino/ArduinoCore-samd/pull/226
