### ISSUE TITLE
Independent dimmer channels

### ISSUE THREAD

**Issue by maxholgasson** [Adminius/DimmerZero#2]
Hi, I can't get your code running as I need 6 independent pwm channels. So far the react all the same I can't control them seperatly.
How can you control channels separate?

**Comment by Adminius** [comment]
what do you mean with separate?
PWM frequencies?
PWM duty-cycle?

can you post an example of you code?

In my examples I control 2 channels with same frequency, but different duty-cycle:
https://github.com/Adminius/DimmerZero/blob/master/examples/DimmerTest/DimmerTest.ino

**Comment by maxholgasson** [comment]
Oh sorry, I intended to post in the forked library "BriscoeTech/PWM_SamD21" because 
I need a higher frequency to control a dc motor.
Your lib is working perfectly but the frequency is unfortunatly too low and the motor as a consequence much to loud

**Comment by Adminius** [comment]
yes, I know, i made it for LEDs.
